[package]
name = "space-comp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
enum-map = "2.4.2"
nalgebra = "0.32.1"
rand = "0.8.5"
rtbvh = "0.6.2"
